/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sen_com_fixndk_fixcore_DexManager */

#ifndef _Included_sen_com_fixndk_fixcore_DexManager
#define _Included_sen_com_fixndk_fixcore_DexManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sen_com_fixndk_fixcore_DexManager
 * Method:    replace
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/reflect/Method;)V
 */
JNIEXPORT void JNICALL Java_sen_com_fixndk_fixcore_DexManager_replace
  (JNIEnv *, jobject,jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
