/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dongnaoedu_live_jni_PushNative */

#ifndef _Included_com_dongnaoedu_live_jni_PushNative
#define _Included_com_dongnaoedu_live_jni_PushNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dongnaoedu_live_jni_PushNative
 * Method:    sendVideo
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_dongnaoedu_live_jni_PushNative_sendVideo
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_dongnaoedu_live_jni_PushNative
 * Method:    sendAudio
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_dongnaoedu_live_jni_PushNative_sendAudio
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_dongnaoedu_live_jni_PushNative
 * Method:    startPush
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dongnaoedu_live_jni_PushNative_startPush
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_dongnaoedu_live_jni_PushNative
 * Method:    stopPush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dongnaoedu_live_jni_PushNative_stopPush
  (JNIEnv *, jobject);

/*
 * Class:     com_dongnaoedu_live_jni_PushNative
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_dongnaoedu_live_jni_PushNative_release
  (JNIEnv *, jobject);

/*
 * Class:     com_dongnaoedu_live_jni_PushNative
 * Method:    setVideoOptions
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_dongnaoedu_live_jni_PushNative_setVideoOptions
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_dongnaoedu_live_jni_PushNative
 * Method:    setAudioOptions
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_dongnaoedu_live_jni_PushNative_setAudioOptions
  (JNIEnv *, jobject, jint, jint);

//发送普通帧
void add_x264_body(unsigned char* buf, int len);
//将pps 和sps 添加到关键帧并发送
void add_sueque_header(unsigned char* sps, unsigned char* pps, int sps_len, int pps_len);

#ifdef __cplusplus
}
#endif
#endif
