/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sen_com_senlive_natives_PushNative */

#ifndef _Included_sen_com_senlive_natives_PushNative
#define _Included_sen_com_senlive_natives_PushNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sen_com_senlive_natives_PushNative
 * Method:    sendVideo
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_sen_com_senlive_natives_PushNative_sendVideo
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     sen_com_senlive_natives_PushNative
 * Method:    sendAudio
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_sen_com_senlive_natives_PushNative_sendAudio
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     sen_com_senlive_natives_PushNative
 * Method:    startPush
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sen_com_senlive_natives_PushNative_startPush
  (JNIEnv *, jobject, jstring);

/*
 * Class:     sen_com_senlive_natives_PushNative
 * Method:    stopPush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sen_com_senlive_natives_PushNative_stopPush
  (JNIEnv *, jobject);

/*
 * Class:     sen_com_senlive_natives_PushNative
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sen_com_senlive_natives_PushNative_release
  (JNIEnv *, jobject);

/*
 * Class:     sen_com_senlive_natives_PushNative
 * Method:    setVideoOptions
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_sen_com_senlive_natives_PushNative_setVideoOptions
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     sen_com_senlive_natives_PushNative
 * Method:    setAudioOptions
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_sen_com_senlive_natives_PushNative_setAudioOptions
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
