/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sen_com_audio_AudioTest */

#ifndef _Included_sen_com_audio_AudioTest
#define _Included_sen_com_audio_AudioTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sen_com_audio_AudioTest
 * Method:    sound
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sen_com_audio_AudioTest_sound
        (JNIEnv *, jobject, jstring, jstring);
JNIEXPORT void JNICALL Java_sen_com_audio_AudioTest_sound2
        (JNIEnv *, jobject, jstring, jstring);
JNIEXPORT void JNICALL Java_sen_com_audio_AudioTest_playSound
        (JNIEnv *, jobject, jstring, jstring);
JNIEXPORT void JNICALL Java_sen_com_audio_AudioTest_playSoundInThread
        (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
