/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sen_com_ffmpegstudy06_FFmpegTest */

#ifndef _Included_sen_com_ffmpegstudy06_FFmpegTest
#define _Included_sen_com_ffmpegstudy06_FFmpegTest
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_sen_com_ffmpegstudy06_FFmpegTest_getConfigInfo
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_sen_com_ffmpegstudy06_FFmpegTest_readVideoInfoOldApi
        (JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL Java_sen_com_ffmpegstudy06_FFmpegTest_readVideoInfoNewApi
        (JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL Java_sen_com_ffmpegstudy06_FFmpegTest_readFileInfoNewFromLaoShi
        (JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL Java_sen_com_ffmpegstudy06_FFmpegTest_callFFmpegOldDecode
        (JNIEnv *, jobject, jstring, jstring);
JNIEXPORT void JNICALL Java_sen_com_ffmpegstudy06_FFmpegTest_callFFmpegOldDecodeLaoShi
        (JNIEnv *, jobject, jstring, jstring);
JNIEXPORT void JNICALL Java_sen_com_ffmpegstudy06_FFmpegTest_callFFmpegNewDecode
        (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
