/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sen_com_thread_PThread */

#ifndef _Included_sen_com_thread_PThread
#define _Included_sen_com_thread_PThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sen_com_thread_PThread
 * Method:    createThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sen_com_thread_PThread_createThread
        (JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_sen_com_thread_PThread_destroy
        (JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_sen_com_thread_PThread_init
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
