/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sen_com_video_VideoAudioPlay */

#ifndef _Included_sen_com_video_VideoAudioPlay
#define _Included_sen_com_video_VideoAudioPlay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sen_com_video_VideoAudioPlay
 * Method:    videoAudio
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sen_com_video_VideoAudioPlay_videoAudio
  (JNIEnv *, jobject, jstring,jstring , jobject);
JNIEXPORT void JNICALL Java_sen_com_video_VideoAudioPlay_playSoundInThread
        (JNIEnv *, jobject, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
