/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sen_com_video_VideoPlayContrlor */

#ifndef _Included_sen_com_video_VideoPlayContrlor
#define _Included_sen_com_video_VideoPlayContrlor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sen_com_video_VideoPlayContrlor
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sen_com_video_VideoPlayContrlor_render
  (JNIEnv *, jobject,jstring,jobject);




#ifdef __cplusplus
}
#endif
#endif
