/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sen_com_video_VideoAudioPlay */

#ifndef _Included_sen_com_video_VideoAudioPlay
#define _Included_sen_com_video_VideoAudioPlay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sen_com_video_VideoAudioPlay
 * Method:    videoAudio
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */

JNIEXPORT void JNICALL Java_sen_com_video_VideoAudioPlay_videoAudioPlayerV2
        (JNIEnv *, jobject, jstring, jstring, jobject);


//给AVPacket 开辟空间，后面会将AVPacket栈内存数据拷贝到这里
void* player_fill_packet();
//解码Video前进行初始化准备

#ifdef __cplusplus
}
#endif
#endif
