/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sen_com_ndk_image_NdkImage */

#ifndef _Included_sen_com_ndk_image_NdkImage
#define _Included_sen_com_ndk_image_NdkImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sen_com_ndk_image_NdkImage
 * Method:    ndkimage
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_sen_com_ndk_1image_NdkImage_ndkimage
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
